on:
  push:
    branches:
      - master

name: Protoconf insert to production
jobs:
  checks:
    name: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: insert ams3c01
        uses: protoconf/protoconf-actions@master
        env:
          CONSUL_CAPATH: ${GITHUB_WORKSPACE}/src/infra/protoconf_ca.crt
        with:
          store_type: consul
          store_address: https://consul.service.ams3c01.pco.nf:8501
          prefix: production
          before_commit: ${{ github.event.before }}
          after_commit: ${{ github.event.after }}
      - name: insert lon1c01
        uses: protoconf/protoconf-actions@master
        env:
          CONSUL_CAPATH: ${GITHUB_WORKSPACE}/src/infra/protoconf_ca.crt
        with:
          store_type: consul
          store_address: https://consul.service.lon1c01.pco.nf:8501
          prefix: production
          before_commit: ${{ github.event.before }}
          after_commit: ${{ github.event.after }}
